# Generated by Django 4.0.3 on 2022-03-31 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouct',
            new_name='Product',
        ),
    ]
